<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/3/19
 * Time: 15:15
 */

namespace Cool\Foundation;


use Cool\Contracts\Foundation\ComponentInterface;
use Cool\Foundation\Bean\AbstractObject;
use Cool\Foundation\Container\ContainerManager;
use Cool\Foundation\Exceptions\ConfigException;
use Cool\Support\FileSystem;

class Application  extends AbstractObject implements \ApplicationInterface
{

    /**
     * 应用名称
     * @var string
     */
    public $appName = 'app-console';

    /**
     * 应用版本
     * @var string
     */
    public $appVersion = '0.0.0';

    /**
     * 应用调试
     * @var bool
     */
    public $appDebug = true;

    /**
     * 基础路径
     * @var string
     */
    public $basePath = '';

    /**
     * 配置路径
     * @var string
     */
    public $configPath = 'config';

    /**
     * 运行目录路径
     * @var string
     */
    public $runtimePath = 'runtime';

    /**
     * 组件配置
     * @var array
     */
    public $components = [];

    /**
     * 依赖配置
     * @var array
     */
    public $beans = [];

    /**
     * 容器
     * @var  Container\container
     */
    public $container;

    /**
     * 初始化事件
     */
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 快捷引用
        \Cool::$app = $this;
        // 实例化容器
        $this->container = new ContainerManager([
            'config' => $this->components,
        ]);
        // 错误注册
        Error::register();
    
    }

    /**
     * 判断组件是否存在
     * @param $name
     * @return bool
     */
    public function isRegistered($name)
    {
        return isset($this->components[$name]) ? true : false;
    }

    /**
     * 判断组件是否在执行
     * @param $name
     * @return bool
     */
    public function isRunning($name)
    {
        if (!$this->container->has($name)) {
            return false;
        }
        $component = $this->container->get($name);
        return $component->getStatus() == ComponentInterface::STATUS_RUNNING ? true : false;
    }

    /**
     * 获取配置
     * @param $name
     * @return mixed
     */
    public function config($name)
    {
        $message   = "Config does not exist: {$name}.";
        $fragments = explode('.', $name);
        // 判断一级配置是否存在
        $first = array_shift($fragments);
        if (!isset($this->$first)) {
            throw new ConfigException($message);
        }
        // 判断其他配置是否存在
        $current = $this->$first;
        foreach ($fragments as $key) {
            if (!isset($current[$key])) {
                throw new ConfigException($message);
            }
            $current = $current[$key];
        }
        return $current;
    }

    /**
     * 获取配置目录路径
     * @return string
     */
    public function getConfigPath()
    {
        if (!FileSystem::isAbsolute($this->configPath)) {
            if ($this->configPath == '') {
                return $this->basePath;
            }
            return $this->basePath . DIRECTORY_SEPARATOR . $this->configPath;
        }
        return $this->configPath;
    }

    /**onInitialize
     * 获取运行目录路径
     * @return string
     */
    public function getRuntimePath()
    {
        if (!FileSystem::isAbsolute($this->runtimePath)) {
            if ($this->runtimePath == '') {
                return $this->basePath;
            }
            return $this->basePath . DIRECTORY_SEPARATOR . $this->runtimePath;
        }
        return $this->runtimePath;
    }

}