<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/3/21
 * Time: 16:57
 */

namespace Cool\Database\Pool;


use Cool\Contracts\Pool\ConnectionPoolInterface;
use Cool\Pool\AbstractConnectionPool;

class ConnectionPool extends AbstractConnectionPool implements ConnectionPoolInterface
{
    /**
     * 获取连接
     * @return \Cool\Database\Coroutine\PDOConnection
     */
    public function getConnection()
    {
        return parent::getConnection(); // TODO: Change the autogenerated stub
    }
}