<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2019/3/20
 * Time: 17:08
 */

namespace Cool\Redis\Pool;


use Cool\Contracts\Pool\ConnectionPoolInterface;
use Cool\Pool\AbstractConnectionPool;
use Cool\Redis\Coroutine\RedisConnection;

class ConnectionPool extends AbstractConnectionPool implements ConnectionPoolInterface
{
    /**
     * 获取连接
     * @return RedisConnection
     */
    public function getConnection()
    {
        return parent::getConnection(); // TODO: Change the autogenerated stub
    }
}